version: '3.7'

services:
  postgresql:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    env_file:
      - .env
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: unless-stopped
